services:
  backend:
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: webapp/Dockerfile
    volumes:
      - .:/app
    command: uvicorn webapp.main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    networks:
      - netweb

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - /home/accelerator/certificate.crt:/home/accelerator/certificate.crt
      # - /home/accelerator/certificate.key:/home/accelerator/certificate.key
    networks:
      - netweb

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - netweb
  
volumes:
  postgres_data:

networks:
  netweb:
    external: true